# Generated by Django 5.0.14 on 2026-07-20 18:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ciudad', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='BitacoraCompletado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tarea', models.CharField(max_length=255)),
                ('maquina', models.CharField(default='-', max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_cierre', models.DateField()),
                ('dias_duracion', models.IntegerField(default=0)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.empresa')),
            ],
            options={
                'db_table': 'bitacora_completados',
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('tarea_1', models.CharField(default='-', max_length=255)),
                ('avance_1', models.IntegerField(default=0)),
                ('fecha_inicio_1', models.DateField(blank=True, null=True)),
                ('maquina_1', models.CharField(default='-', max_length=255)),
                ('tarea_2', models.CharField(default='-', max_length=255)),
                ('avance_2', models.IntegerField(default=0)),
                ('fecha_inicio_2', models.DateField(blank=True, null=True)),
                ('maquina_2', models.CharField(default='-', max_length=255)),
                ('tarea_3', models.CharField(default='-', max_length=255)),
                ('avance_3', models.IntegerField(default=0)),
                ('fecha_inicio_3', models.DateField(blank=True, null=True)),
                ('maquina_3', models.CharField(default='-', max_length=255)),
                ('tarea_4', models.CharField(default='-', max_length=255)),
                ('avance_4', models.IntegerField(default=0)),
                ('fecha_inicio_4', models.DateField(blank=True, null=True)),
                ('maquina_4', models.CharField(default='-', max_length=255)),
                ('tarea_5', models.CharField(default='-', max_length=255)),
                ('avance_5', models.IntegerField(default=0)),
                ('fecha_inicio_5', models.DateField(blank=True, null=True)),
                ('maquina_5', models.CharField(default='-', max_length=255)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.empresa')),
            ],
            options={
                'db_table': 'bitacora',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.empresa')),
            ],
            options={
                'db_table': 'usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PrestamoHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajador', models.CharField(max_length=100)),
                ('herramienta', models.CharField(max_length=255)),
                ('tarea', models.CharField(max_length=255)),
                ('fecha_prestamo', models.DateTimeField()),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Prestado', 'Prestado'), ('Devuelto', 'Devuelto')], default='Prestado', max_length=20)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.empresa')),
            ],
            options={
                'db_table': 'prestamo_herramientas',
            },
        ),
        migrations.CreateModel(
            name='ProductoInventario',
            fields=[
                ('clave', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('stock', models.IntegerField(default=0)),
                ('orden', models.CharField(blank=True, max_length=100, null=True)),
                ('obra', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=20)),
                ('piezas', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('solicitante', models.CharField(blank=True, max_length=100, null=True)),
                ('maquina', models.CharField(blank=True, max_length=100, null=True)),
                ('obra', models.CharField(blank=True, max_length=100, null=True)),
                ('orden', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='nucleo.productoinventario')),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maquina', models.CharField(max_length=255)),
                ('motivo', models.CharField(max_length=255)),
                ('fecha_ingreso', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('En Taller', 'En Taller'), ('Reparado', 'Reparado')], default='En Taller', max_length=20)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.empresa')),
            ],
            options={
                'db_table': 'taller',
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.empresa')),
            ],
            options={
                'db_table': 'maquinas',
                'unique_together': {('empresa', 'nombre')},
            },
        ),
    ]
